### Subtopics for Analysis
- OpenStreetMaps + Matplotlib plotting
    - Make a radius of incident around crime and quantify the number of alcohol licensed stores are in vicinity
- Type of crime (white-collar, violent, drug, etc.) 
- Type of liquor licenses
- If store hours (opening and closing times) effect "HOUR of CRIME"
- By year
- TODO, Add to this list
- Honestly, you could even get more qualitative info by contacting store for personal accounts???

In [9]:
import pandas as pd
import numpy as np
import matplotlib

# DOC
# https://docs.google.com/document/d/1ulitc7RCGT-E3OTpzrvW5x3W-CBC22PNf_T4PX4M-J0/edit#heading=h.f8bdqhhsu722

In [10]:
raw_alc_license_df = pd.read_csv('blb_section_12_alcohol.csv')
raw_alc_license_df.head()

,license_num,historicallicensenum,status,license_type,issued,expires,business_name,dba_name,comments,location_comments,...,applicant,manager,day_phone,evening_phone,address,city,state,zip,gpsx,gpsy
0,LB-418523,NaN,Active,Retail Malt Wine,2020-07-30,2020-12-31,OLKA Corporation,7-Eleven,NO SINGLES,"Single floor convenience store approx 3,540 sq...",...,OLKA Corporation,Oltion Kadilli,(617)426-2746,NaN,55 Berkeley ST,Boston,MA,02116,772278.999995,2.951600e+06
1,LB-427987,NaN,Active,Retail Malt Wine,2020-07-30,2020-12-31,"The Daily Market, LLC","The Daily Market, LLC",NaN,The premises includes a portion of the basemen...,...,"The Daily Market, LLC",John C. McDonough,NaN,NaN,104 Savin Hill Av,Dorchester,MA,02125,776838.376864,2.939016e+06
2,LB-423824,NaN,Active,Retail Malt Wine,2020-05-19,2020-12-31,"Verc Enterprises, LLC",Verc Allston Gulf,NO SINGLES,NaN,...,"Verc Enterprises, LLC",Nekita T. Martin,(617)782-1224,NaN,198 Western AVE,Allston,MA,02134,756044.793953,2.957524e+06
3,LB-410009,NaN,Active,CV7 All Alc. Airp.,2020-03-04,2020-12-31,"SSP America BOS, LLC",Wahlburgers,NaN,"3,033 sq. ft. restaurant located within Termi...",...,"SSP America BOS, LLC",Jacqueline Genao,(781)808-8354,NaN,Logan Airport 300 Terminal C,East Boston,MA,02128,0.000000,0.000000e+00
4,LB-423834,NaN,Active,BYOB Bring Your Own Bottle,2020-02-20,2020-12-31,"Food For Thought, LLC",Food For Thought Test Kitchen,<STRONG><FONT size=5></FONT></STRONG>,"One floor, one room, one bathroom, a divided b...",...,"Food For Thought, LLC",Jan Grey,(617)567-0058,NaN,567 Bennington ST,Boston,MA,02128,786350.973004,2.964777e+06

In [11]:
for col in raw_alc_license_df.columns: print(col)

license_num
historicallicensenum
status
license_type
issued
expires
business_name
dba_name
comments
location_comments
opening
closing
patronsout
capacity
applicant
manager
day_phone
evening_phone
address
city
state
zip
gpsx
gpsy

In [12]:
raw_crime_df = pd.read_csv('crime-incident-reports-2015.csv')
raw_crime_df.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I192068249,2647,Other,THREATS TO DO BODILY HARM,B2,280,NaN,2015-08-28 10:20:00,2015,8,Friday,10,Part Two,WASHINGTON ST,42.330119,-71.084251,"(42.33011862, -71.08425106)"
1,I192061894,1106,Confidence Games,FRAUD - CREDIT CARD / ATM FRAUD,C11,356,NaN,2015-08-20 00:00:00,2015,8,Thursday,0,Part Two,CHARLES ST,42.300605,-71.061268,"(42.30060543, -71.06126785)"
2,I192038828,1107,Fraud,FRAUD - IMPERSONATION,A1,172,NaN,2015-11-02 12:24:00,2015,11,Monday,12,Part Two,ALBANY ST,42.334288,-71.072395,"(42.33428841, -71.07239518)"
3,I192008877,1107,Fraud,FRAUD - IMPERSONATION,E18,525,NaN,2015-07-31 10:00:00,2015,7,Friday,10,Part Two,WINGATE RD,42.237009,-71.129566,"(42.23700950, -71.12956606)"
4,I182090828,1102,Fraud,FRAUD - FALSE PRETENSE / SCHEME,D4,159,NaN,2015-12-01 12:00:00,2015,12,Tuesday,12,Part Two,UPTON ST,42.342432,-71.072258,"(42.34243222, -71.07225766)"

In [13]:
for col in raw_crime_df.columns: print(col)

INCIDENT_NUMBER
OFFENSE_CODE
OFFENSE_CODE_GROUP
OFFENSE_DESCRIPTION
DISTRICT
REPORTING_AREA
SHOOTING
OCCURRED_ON_DATE
YEAR
MONTH
DAY_OF_WEEK
HOUR
UCR_PART
STREET
Lat
Long
Location